apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: simple-nodejs-app-uslj
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: simple-nodejs-app-uslj
    app.kubernetes.io/part-of: nodejs-users
  name: simple-nodejs-app-uslj
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: simple-nodejs-app-uslj
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: simple-nodejs-app-uslj
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-iweq-tenant/nodejs-users/simple-nodejs-app-uslj@sha256:c659592bd65d143560449a6f4c1b651cc9e608ca5da8194521d5e839d47cb3bb
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
